# Generated by Django 2.0 on 2019-10-25 15:27

from django.db import migrations, models
import django.db.models.manager
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone', models.CharField(default='', editable=False, max_length=10)),
                ('name', models.CharField(default='', editable=False, max_length=50)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='pgmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('available', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('any', 'Any')], default='', editable=False, max_length=100)),
                ('occupancy', models.CharField(choices=[('single', 'Single'), ('sharing', 'Sharing')], max_length=100)),
                ('balcony', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=100)),
                ('parking', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=100)),
                ('food', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', editable=False, max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('details', multiselectfield.db.fields.MultiSelectField(choices=[('A.C', 'A.C'), ('TV', 'TV'), ('Fridge', 'Fridge'), ('Washing Machine', 'Washing Machine'), ('Wi-fi', 'Wi-fi')], default='', editable=False, max_length=100)),
            ],
        ),
    ]
